<?xml version="1.0" encoding="UTF-8" ?>
<!--<!DOCTYPE students SYSTEM "student.dtd">-->
<!DOCTYPE students[    <!--内部引用-->
		<!ELEMENT students (student*) >  <!--*表示出现0次或者多次-->
		<!ELEMENT student (name,age,sex)> <!--表示student标签中能出现name、age、sex标签，只能出现一次，顺序也要一致-->
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT age (#PCDATA)>   <!-- #PCDATA表示字符串-->
		<!ELEMENT sex (#PCDATA)>
		<!ATTLIST student number ID #REQUIRED> <!--#REQUIRED表示笔数出现-->
		]>
<students>
	<student number="studentB">
		<name>Gallagher</name>
		<age>24</age>
		<sex>male</sex>
	</student>
</students>
<!--
<students>
	<student number="studentA">
		<name>Gallagher</name>
		<age>24</age>
		<sex>male</sex>
	</student>
</students>-->
